Make remaining functions in clientthread.cpp depend on ThreadedClient.
Exception: client_io_thread(). That will wait until ThreadedClient is a component of Client.